# Generated by Django 3.0.5 on 2020-07-26 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_auto_20200727_0158'),
        ('auth', '0011_update_proxy_permissions'),
        ('admin', '0004_auto_20200727_0158'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StarnaviUser',
            new_name='SocialUser',
        ),
        migrations.RenameField(
            model_name='dislike',
            old_name='dislike_published',
            new_name='disliked_at',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='like_published',
            new_name='liked_at',
        ),
        migrations.AlterField(
            model_name='dislike',
            name='dislike_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike_user', to=settings.AUTH_USER_MODEL, to_field='id'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to=settings.AUTH_USER_MODEL, to_field='id'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, to_field='id', verbose_name='Author post'),
        ),
    ]
